### ISSUE TITLE
Page crashes after playing transcript for a while

### ISSUE THREAD

**Issue by dubem-design** [hyperaudio/hyperaudio-lite#123]
I implemented hyperaudio-lite on a website and it returns the error shown in the screenshot below. Anyone have an idea what the issue might be?

Environment: Gridsome, hyperaudio is initialized from mounted hook.

<img width="1389" alt="Screenshot 2022-09-26 at 09 04 01" src="https://user-images.githubusercontent.com/21142183/192227598-aaf7977c-1990-4e27-ac7e-7c0525e008cc.png">

**Comment by maboa** [comment]
Sorry, but I have never encountered a crash like that using Hyperaudio Lite. I suspect it's unrelated to Hyperaudio Lite itself but without further information it's hard to say for sure, so I'm closing the issue but still happy to discuss in this thread.
