### ISSUE TITLE
Spotify podcast player support?

### ISSUE THREAD

**Issue by andreashorn** [hyperaudio/hyperaudio-lite#156]
We would love for hyperaudio to support the player from spotify / podcasts (example here:
https://stimulatingbrains.org/39-nico-dosenbach-a-bold-challenge-to-penfields-homunculus-based-on-resting-state-fmri/)

Could that be feasible? 

Thank you so much for considering!

**Comment by maboa** [comment]
Yes! Absolutely @andreashorn ! I just came here to create that issue off the back of this request in the wordpress plugin repo https://github.com/hyperaudio/wordpress-hyperaudio/issues/120

Looks like it's [all possible](https://developer.spotify.com/documentation/web-api).

**Comment by andreashorn** [comment]
Thanks so much!
Any ideas re time line for this (we are considering uploading mp3s additionally instead but if we can get the spotify player to work that would be much preferred for us)?
Thanks! A

**Comment by maboa** [comment]
Sure, no problem! I'll look into it some time this month [since others are asking about it](https://github.com/hyperaudio/wordpress-hyperaudio/discussions/119#discussioncomment-7197867).

**Comment by maboa** [comment]
This looks like the API we need to use https://developer.spotify.com/documentation/embeds/references/iframe-api#methods

**Comment by maboa** [comment]
A beta version of the player is now implemented https://github.com/hyperaudio/hyperaudio-lite/pull/178 cc @andreashorn
