### ISSUE TITLE
Vidstack Support Request

### ISSUE THREAD

**Issue by Montassar22** [hyperaudio/hyperaudio-lite#186]
Could you consider integrating Vidstack into Hyperaudio? Given the growing popularity of Vidstack, It offers advanced video features that could enhance Hyperaudio's capabilities.
Thank you,

**Comment by maboa** [comment]
I will certainly take a look at it. Thanks for the suggestion @Montassar22

**Comment by maboa** [comment]
@Montassar22 It turns out that Hyperaudio was already compatible, but you need to explicitly set the `data-player-type` as `native`. Example here https://github.com/hyperaudio/hyperaudio-lite/blob/main/vidstack.html#L42-L47
