### ISSUE TITLE
Strikethrough/Redaction doesn't work when including punctuation

### ISSUE THREAD

**Issue by overZellis133** [hyperaudio/hyperaudio-lite#198]
<img width="1440" alt="Screen_Shot_2024-07-19_at_3_04_24_PM" src="https://github.com/user-attachments/assets/5269705e-11bd-49df-930c-34266a4d96cb">

redaction doesn’t work when the punctuation is included in the strikethrough. E.g. when striking through “creation of captions and interactive transcripts.”

If striking through instead, “creation of captions and interactive transcripts” redaction works as expected.

**Comment by maboa** [comment]
Closing, as this is an issue for https://github.com/hyperaudio/hyperaudio-lite-editor/
